language: node_js
node_js:
  - '8'
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
  - npm run install:demo
  - npm run build
before_script: greenkeeper-lockfile-update
script:
  - npm run lint
after_script: greenkeeper-lockfile-upload
notifications:
  email: false
  slack:
    rooms:
      secure: Ui4LMaK32uHj9LIMH6XrEgVQq2NJLUZci8hRUqwKf0qanfovYsva+E6irRmbm88M2aKtumXPDOk8Ir+zgXKhOu4XIEBuT/OHri9og8PiTz4tMC4EOLSO/XBo+c/6GI0/kbZg4t37gyh7joIox9O7zhARbjCp1bvQkwlNzB97xbWqUatVn2+FTv1eJOSM7CbrzXDm7j8x2G8fpMsg1V6+zv8q1crmJlqNCqlkMgchsoUm4J839GzBtbDYmD73lpHaOdhb0HkoczGHuv2gtP+4O2gEohvn2PX+XB7FzwsnE3ejkxzkJMEcmuPpgelUeB53ZENsya1WMDiOogXCYi41Z6QQBGZFoYforR5L80SYbIOY8nTK0JSoRwgmrve3Egrc+Pf25AqXJj8I1LnSOYce7AFrzmjIs9m02SCQWLv1jb2AJMRqYeJ1Pfl/tt1Y/rRFBMZhCPytzrREZ1tcDCOkoBhK27bHYQTuR4O94FsBqh/voFx0UYrSNdhCoxvvWh1mZd56kuzBBcggXQvWymYzNK9mQP9qVT0XZ8Y8BU93lYuCNrooMMe54iJ1w44PRnDTV4PcqfQO+MR6+NymzkiRbwbCLpc9/gQrbNbYSu30f6nVrtUdXMLnqfeEV5IAVazKqfxglxOlDcF/0s2n2uqLh1WOhje9KHmULvfdPs8FhZc=
    on_success: change
