language: node_js
node_js:
  - '8'
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
  - npm run install:demo
  - npm run build
before_script: greenkeeper-lockfile-update
script:
  - npm run lint
after_script: greenkeeper-lockfile-upload
notifications:
  email: false
  slack:
    rooms:
      secure: gXideq8q2sKqjpjkWho4aOKIawx2huKl7+mbH8VZsZTcK8q2jAhLq3V4MjNUoVzZEHh7iK5K+dtWBEaGZsa/xsQF7Mu/WuH0VcNn0XgQzHLK4oO1KK/cIVr+Kb+RyHzNWudY/pXamW++YqTh3u5Wckn3oo5KCKecclSvPiWS1lQdnAdWq/RWutzXNITTZyDvgrr2UcvUey75R/oJ2P2Fr68epFVBnFB/xJFpi9i6HHciBE9mioTy+xk/WezhmtyUxe1jCDNFf8/jamihEltRjCmzDwuXcnEHkSW8v/f4KUPPDVHA6WdJT5l/2WWX/WzOxMKgkiBJ0hZd7baHcxlHnH1vbBBbeE6eaPuac2ztZ9rj/nfB/xB0ZArtp1O0gfMME+1i/YpNO3eIwBIJkR2hYRo5vVzJmmTKIgxJb2Xz6lx3pLe3dIC/D0f+VK4BbGfLSHghXuj+JYFF8RgFEpYIdkXuAKwVy3hjSpydt9y6p6Q72nnU/fbMQAssbSCwXcB5FBKAmFXJzPg6csYD2ZHG3Z0rJSJzN6XLPzCIDZoPB0mBeXovHx0u9rV8ffhFMpWkC4sFAwH3iXyd6Vuq25XbNDCqYH+70bQDd8LCLeQbNuRqV6UKKxs9FxCTONp0dRl2rXZRw0SaSKcH4mn/m/gPelGsJYkwY7CCO9udf4EPyhM=
    on_success: change
